#####################################################################
2023-06-16 01:28:13.844137+09:00
카테고리는 react 로 하겠습니다.
StackAPI 오류발생 :  list index out of range
프로그램 종료.
#####################################################################
2023-06-16 01:29:20.994305+09:00
카테고리는 react 로 하겠습니다.
주제는 You&#39;re importing a component that needs useState. It only works in a Client Component, but none of its parents are marked with &quot;use client&quot; 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-16 01:29:48.771734+09:00
카테고리는 react 로 하겠습니다.
주제는 How to get the current pathname in the app directory of Next.js 13? 로 하겠습니다.
Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 120, in <module>
    title_response = generate_blog_to_title(topic)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 66, in generate_blog_to_title
    return generate_response(prompt, max_tokens=100, temperature=0.2)
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 45, in generate_response
    completion = openai.ChatCompletion.create(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/yoon/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoon/ChatGPT/ChatGPT-blog/main.py", line 126, in <module>
    print("title", title)
NameError: name 'title' is not defined. Did you mean: 'time'?
#####################################################################
2023-06-16 01:34:33.086752+09:00
카테고리는 react 로 하겠습니다.
주제는 Next.js 13 throws 3 errors out of the box after starting a new project 로 하겠습니다.
제목 만들었습니다. "Troubleshooting Initial Errors in Next.js 13: A Comprehensive Guide" : 94
본문 1/2 만들었습니다. : 1146
본문 2/2 만들었습니다. : 1152
참고할만한 사이트를 만들었습니다. "Troubleshooting Initial Errors in Next.js 13: A Comprehensive Guide" : 274
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
#####################################################################
2023-06-16 19:00:01.701513+09:00
카테고리는 react 로 하겠습니다.
주제는 Zustand fetch with API call useEffect best practice 로 하겠습니다.
제목 만들었습니다. "Best Practices for Using Zustand Fetch with API Call in useEffect" : 84
본문 1/2 만들었습니다. : 1394
본문 2/2 만들었습니다. : 1158
참고할만한 사이트를 만들었습니다. "Best Practices for Using Zustand Fetch with API Call in useEffect" : 278
파일을 생성하기 전 잠깐 기다립니다.
파일을 생성하겠습니다.
모든 작업이 끝났습니다.
#####################################################################
